# Docker Compose configuration for local storage with persistent volume
#
# IMPORTANT: Update the following before running:
# - Image TAG: Replace with specific version or 'latest'

version: '3.8'

services:
  secure-secret-share:
    image: ghcr.io/nckslvrmn/secure_secret_share:TAG  # Replace TAG with version (e.g., v1.0.0) or 'latest'
    ports:
      - "8081:8081"
    volumes:
      - secret-data:/data
    restart: unless-stopped

volumes:
  secret-data:
    driver: local